export interface IBaseShift {
    _id?: string,
    title: string,
    facility: string,
    type: string,
    limit: number,
    teamLeader?: string,
    isTeamLeader: boolean,
    isStudentPreferred: boolean,
    agents: any[],
    date: Date,
    length: number,
    isFull: boolean,
    timeLoss?: number,
    isFoodSupplied?: boolean,
    isWeekendActive: boolean,
    createdAt: Date,
    updatedAt: Date,
}